# Generated by Django 6.0.4 on 2026-05-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='plagiarism_score',
            field=models.FloatField(default=0.0),
        ),
    ]
