# Generated by Django 6.0.4 on 2026-05-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submission_plagiarism_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='plagiarism_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
