# Generated by Django 6.0.4 on 2026-05-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_grading_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        # -----------------------------
        # 1. REMOVE OLD ASSIGNMENT RULES
        # -----------------------------
        migrations.RemoveField(
            model_name='assignment',
            name='required_function_name',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='required_param_count',
        ),

        # -----------------------------
        # 2. UPDATE TESTCASE MODEL
        # -----------------------------

        migrations.AddField(
            model_name='testcase',
            name='test_type',
            field=models.CharField(
                max_length=10,
                choices=[
                    ('stdout', 'Stdout (run script, compare output)'),
                    ('function', 'Function (call function, compare return)')
                ],
                default='stdout'
            ),
        ),

        migrations.AddField(
            model_name='testcase',
            name='function_name',
            field=models.CharField(
                max_length=100,
                blank=True,
                help_text='Name of function to call'
            ),
        ),

        migrations.AddField(
            model_name='testcase',
            name='arguments',
            field=models.JSONField(
                default=list,
                blank=True,
                help_text='List of arguments to pass'
            ),
        ),

        migrations.AlterField(
            model_name='testcase',
            name='input_data',
            field=models.TextField(
                blank=True,
                help_text='Input for stdin (only for stdout mode)'
            ),
        ),

        migrations.AlterField(
            model_name='testcase',
            name='expected_output',
            field=models.TextField(
                blank=True,
                help_text='Expected output (stdout mode) or return value (function mode)'
            ),
        ),

        migrations.AlterField(
            model_name='testcase',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),

        # -----------------------------
        # 3. CREATE COURSE MODEL
        # -----------------------------
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, help_text='e.g., HSE211')),
                ('title', models.CharField(max_length=200, help_text='e.g., Introduction to Programming')),
                ('faculty', models.CharField(max_length=100, blank=True, help_text='e.g., Faculty of Computing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),

                ('lecturer', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='courses',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
        ),

        # -----------------------------
        # 4. LINK ASSIGNMENT → COURSE
        # -----------------------------
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(
                to='assignments.course',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='assignments',
            ),
        ),
    ]