# Generated by Django 6.0.4 on 2026-05-14 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_alter_assignment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.course'),
        ),
    ]
