# Generated by Django 6.0.4 on 2026-05-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, help_text="Lecturer's faculty", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reg_number',
            field=models.CharField(blank=True, help_text='Student registration number', max_length=20, null=True),
        ),
    ]
